### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by tyeeman** [hoffa/pt#36]
Finally getting to try this out and I got the exe built. When I run it I get this error - 

```
pt -base-url https://my.site *.md
panic: open *.md: The filename, directory name, or volume label syntax is incorrect.

goroutine 1 [running]:
main.check(0x6dd820, 0xc042060540)
        C:/goWorkspace/src/github.com/hoffa/pt/pt.go:40 +0x51
main.parsePage(0xc042008128, 0x4, 0xc042008110, 0xf, 0x5f255b)
        C:/goWorkspace/src/github.com/hoffa/pt/pt.go:60 +0x90
main.main()
        C:/goWorkspace/src/github.com/hoffa/pt/pt.go:117 +0x240
```
Can you see anything wrong? I have 2 .md files in the same folder as pt.exe. Should they be elsewhere? Why are the GO files shown in my workspace, when everything is supposedly running from the pt.exe alone?

**Comment by hoffa** [comment]
Seems like the shell is passing the literal string `*.md` to the program (which isn't a file, hence the panic). 🤔 I haven't used Windows in a while; does the shell support `*`? Does it work if you pass in the filename directly?

**Comment by tyeeman** [comment]
Yes, the shell supports *, but I will try one filename now.

**Comment by tyeeman** [comment]
Now I get this -

```
pt -base-url https://my.site index.md
panic: template: page.html:7:41: executing "page.html" at <.Summary>: can't evaluate field Summary i
n type *main.Page

goroutine 1 [running]:
main.check(0x6ddc20, 0xc04214a200)
        C:/goWorkspace/src/github.com/hoffa/pt/pt.go:40 +0x51
main.main()
        C:/goWorkspace/src/github.com/hoffa/pt/pt.go:127 +0x58a
```

**Comment by hoffa** [comment]
Try `go get -u github.com/hoffa/pt` (the `-u`'s for update); I removed `.Summary` and a bunch of other fields quite some time ago.

**Comment by hoffa** [comment]
My bad; looks like the template will have to be changed (can use the ones [from here](https://github.com/hoffa/pt/tree/master/templates) for reference).

Only the following fields are supported: 

```go
// FrontMatter represents a page's front matter.
type FrontMatter struct {
	Title   string
	Date    time.Time
	Exclude bool
}

// Page represents a Markdown page with optional front matter.
// The struct is passed to template.html during template execution.
type Page struct {
	*FrontMatter
	Path    string
	URL     htmlTemplate.URL
	Content htmlTemplate.HTML
	Pages   []*Page
}
```

I took the liberty to remove a bunch of features and non-robust fields, sorry it's a bit of a pain. The interface won't be breaking anymore.

**Comment by tyeeman** [comment]
Ok, ran the update command and I'm getting a lot of "Please commit your changes or stash them before you merge" lines showing up in the command window. Also this "error: Your local changes to the following files would be overwritten by merge:"

I got these errors  about a week ago also. I think I ran a couple of commands to get rid of them, like

git reset --hard

shall I try that?

**Comment by hoffa** [comment]
You can run `git stash` (that saves uncommitted changes to a "stash") then `git pull`.

**Comment by tyeeman** [comment]
Ok, did that in the two folder where the errors occured and everything seemed to fix itself. Should I run the pt update command again or should it be working now?

**Comment by hoffa** [comment]
In the `pt` directory, you can do the last two steps from [Examples](https://github.com/hoffa/pt#example) (i.e. except first one, since you already have the templates). That should get you an `index.html`.

**Comment by tyeeman** [comment]
Still got the same errors when I used *.md. I tried each .md file separately and I got the html file created.

So no index file of the pages is created, true? I have to create my own index if I'm making a blog for example?

**Comment by hoffa** [comment]
The index page is created! If you try the steps in Example, you'll see `index.html` is created from `index.md`, and contains the list of posts (you might notice [`templates/page.html`](https://github.com/hoffa/pt/blob/master/templates/page.html) checks `if eq .Path "index.html"`, and adds the list of pages if it is).

**Comment by hoffa** [comment]
I'll close this issue for now, but feel free to reopen if you have any questions!
