### ISSUE TITLE
Footnotes

### ISSUE THREAD

**Issue by charsi** [hoffa/pt#38]
Hi, thanks for sharing pt. I am using it for my site.
Only thing missing I found for my needs was footnotes support. I had to add in blackfriday's footnotes extension to get it working. Here is my patch - https://git.nishil.in/pt/diff/?h=footnotes. Let me know if you want this as a pull request instead.

PS: I use [littlefoot.js](https://goblindegook.github.io/littlefoot/) to turn the footnotes into inline clickable elements like this -

![image](https://user-images.githubusercontent.com/826310/97661965-04232b00-1a33-11eb-93fa-3faaea8a8da8.png)

**Comment by hoffa** [comment]
Hey!
Thanks for using it and thanks for reporting this! 🙌
If you don't mind a PR would be very welcome! I wish `blackfriday` had an option for "just enable everything".

**Comment by charsi** [comment]
I didn't see a way to enable all other than calling them by name. Here are the remaining extensions which are not part of the default set -

```
LaxHTMLBlocks           // Loosen up HTML block parsing rules
HardLineBreak           // Translate newlines into line breaks
TabSizeEight            // Expand tabs to eight spaces instead of four
NoEmptyLineBeforeBlock  // No need to insert an empty line to start a (code, quote, ordered list, unordered list) block
Titleblock              // Titleblock ala pandoc
AutoHeadingIDs          // Create the heading ID from the text
